spring.application.name=broker-backend
spring.docker.compose.enabled=false
broker.config.currencies=TRY
broker.config.redis.host=localhost
broker.config.redis.port=6379
broker.config.locking-time.wait-time-in-seconds=5
broker.config.locking-time.lease-time-in-seconds=10