spring.application.name=broker-backend
spring.docker.compose.enabled=false
broker.config.currencies=TRY
broker.config.redis.host=localhost
broker.config.redis.port=6379
broker.config.locking-time.wait-time-in-seconds=5
broker.config.locking-time.lease-time-in-seconds=10
broker.config.security-config.jwt-secret-key=ca95d02348d793064026b13b6b79920f4cb997c7196e2125269108ef563a21cd0a920be9028a8d7568c2d51335bd0457167e606c0721c497f200fbf1c6fd0006